//
// Autogenerated by Thrift Compiler (0.16.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
import thrift = require('thrift');
import Thrift = thrift.Thrift;
import Q = thrift.Q;
import Int64 = require('node-int64');


declare enum PostTransactionResult {
  MempoolFull = 0,
  Accepted = 1,
}

declare class BlockHeader {
  public slotNo: number;
  public blockHeight: Int64;
  public hash: string;
  public parentHeaderHash?: string;

    constructor(args?: { slotNo: number; blockHeight: Int64; hash: string; parentHeaderHash?: string; });
}
